import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {MongoMemoryReplSet} from 'mongodb-memory-server';
import {connectDatabase} from '../src/db.js';
import {firebaseAdmin} from '../src/firebase-admin.js';
import {createApp} from '../src/app.js';
import {createProvisioner} from '../src/services/provisioning.js';
import {chromium} from 'playwright';
import request from 'supertest';
import {readFile} from 'node:fs/promises';
if(process.env.FIREBASE_PROJECT_ID!=='demo-mongo-audit'||process.env.FIREBASE_AUTH_EMULATOR_HOST!=='127.0.0.1:9298')throw new Error('Tests require isolated audit authentication.');
let mongo,client,database,auth,adminApp,app,store,http,browser;const accounts={},students=[],offers=[];
async function token(email){const response=await fetch('http://127.0.0.1:9298/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=fake-api-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:'DemoPassword123!',returnSecureToken:true})});const result=await response.json();assert.ok(result.idToken,JSON.stringify(result));return result.idToken;}
const api=async(role,path,body)=>request(app).post(path).set('Authorization',`Bearer ${await token(accounts[role].email)}`).send(body);
async function admin(data){const response=await api('admin','/api/admin',data);assert.equal(response.status,200,JSON.stringify(response.body));return response.body;}
before(async()=>{
 mongo=await MongoMemoryReplSet.create({replSet:{storageEngine:'wiredTiger'}});({client,database}=await connectDatabase(mongo.getUri('migration_audit')));const firebase=firebaseAdmin();auth=firebase.auth;adminApp=firebase.app;({app,store}=createApp({database,client,auth,demo:true,origins:['http://127.0.0.1:5050']}));http=app.listen(3001);
 for(const role of ['admin','subject_faculty','mentor','hod','office','library','accounts']){const email=`mongo-${role}@demo.test`,user=await auth.createUser({email,password:'DemoPassword123!',displayName:role});accounts[role]={uid:user.uid,email};await store.doc(`users/${user.uid}`).set({name:role,email,role,department:'ISE',facultyId:role});}
 await store.doc('settings/workflow').set({library:accounts.library.uid,accounts:accounts.accounts.uid,hodId:accounts.hod.uid,officeId:accounts.office.uid});await store.doc('settings/institution').set({allowedDomains:['demo.test'],departments:['ISE'],sections:['A','B','C']});
});
after(async()=>{await browser?.close();await new Promise(resolve=>http?.close(resolve));await client?.close();await adminApp?.delete();await mongo?.stop();});
test('health, valid tokens, invalid tokens and client role spoofing',async()=>{assert.equal((await request(app).get('/health')).status,200);assert.equal((await request(app).post('/api/data/query').send({path:'users'})).status,401);assert.equal((await request(app).get('/api/auth/profile').set('Authorization','Bearer forged')).status,401);const denied=await api('mentor','/api/admin',{action:'savePolicy',role:'admin',policy:{}});assert.equal(denied.status,403);});
test('teacher provisioning and repeated teacher import retain the Auth UID',async()=>{const row={name:'Mongo Teacher Two',collegeEmail:'mongo-teacher-two@demo.test',phone:'9000000000',department:'ISE',employeeId:'MONGO2',role:'subject_faculty'};const result=await admin({action:'importTeacher',row}),repeat=await admin({action:'importTeacher',row});assert.equal(result.uid,repeat.uid);accounts.teacher2={uid:result.uid,email:row.collegeEmail};assert.equal((await auth.getUser(result.uid)).email,row.collegeEmail);});
test('offering CSV semantics resolve exact teachers and preserve context',async()=>{for(const section of ['A','B','C']){const row={department:'ISE',scheme:'2022',semester:5,section,subjectCode:'TEST501',subjectName:'Migration test subject',teacherEmail:section==='B'?accounts.teacher2.email:accounts.subject_faculty.email,credits:'4',components:[{id:'ia1',label:'IA1',max:30},{id:'assignment',label:'Assignment',max:10}]};assert.equal((await admin({action:'previewOfferings',rows:[row]})).valid,1);offers.push({row,...await admin({action:'importOffering',row})});}});
test('student CSV provisioning maps A/B/C students and repeated imports preserve UID/enrollments',async()=>{for(let i=0;i<4;i++){const row={name:i<2?'Duplicate Mongo Name':'Mongo Student '+i,usn:'1AY99IS'+(150+i),collegeEmail:`mongo-student-${i}@demo.test`,phone:'9000000000',department:'ISE',semester:5,section:['A','B','C','B'][i],scheme:'2022',mentorEmail:accounts.mentor.email,role:'student'};const result=await admin({action:'provision',row,requestId:'mongo-student-'+i});students.push({row,...result});accounts['student'+i]={uid:result.uid,email:row.collegeEmail};const repeat=await admin({action:'provision',row,requestId:'mongo-repeat-'+i});assert.equal(repeat.uid,result.uid);assert.equal(await database.collection('enrollments').countDocuments({studentId:result.uid}),1);const enrollment=await database.collection('enrollments').findOne({studentId:result.uid});assert.equal(enrollment.section,row.section);}});
test('late offering import backfills all matching students and does not replace marks',async()=>{const row={...offers[1].row,subjectCode:'TEST502'},result=await admin({action:'importOffering',row});assert.equal(await database.collection('enrollments').countDocuments({offeringId:result.id}),2);assert.equal((await admin({action:'importOffering',row})).id,result.id);assert.equal(await database.collection('enrollments').countDocuments({offeringId:result.id}),2);});
test('teacher roster is scoped and student marks remain independent',async()=>{const enrolled=await database.collection('enrollments').find({offeringId:offers[1].id}).toArray();for(let i=0;i<enrolled.length;i++){const result=await api('teacher2','/api/data/write',{operations:[{type:'set',path:'marks/'+enrolled[i]._id,data:{scores:{ia1:10+i,assignment:4+i}}}]});assert.equal(result.status,200,JSON.stringify(result.body));}assert.notDeepEqual((await database.collection('marks').findOne({_id:enrolled[0]._id})).scores,(await database.collection('marks').findOne({_id:enrolled[1]._id})).scores);const response=await api('subject_faculty','/api/data/read',{path:'students/'+students[1].uid});assert.equal(response.status,403);const own=await api('student1','/api/data/query',{path:'marks',filters:[['studentId','==',students[1].uid]]});assert.equal(own.body.rows.length,1);const ownClasses=await api('teacher2','/api/data/query',{path:'offerings',filters:[]});assert.ok(ownClasses.body.rows.every(r=>r.data.teacherId===accounts.teacher2.uid));});
test('mentor sees assigned mentees and unrelated profiles stay private',async()=>{const response=await api('mentor','/api/data/query',{path:'students'});assert.equal(response.body.rows.length,4);assert.equal((await api('student0','/api/data/read',{path:'students/'+students[1].uid})).status,403);});
let requestId;
test('request has exact teacher approvals, Library/Accounts and no lab approvals',async()=>{const response=await api('student1','/api/requests',{});assert.equal(response.status,200,JSON.stringify(response.body));requestId=response.body.id;const r=(await store.doc('noDueRequests/'+requestId).get()).data();assert.equal(Object.keys(r.approvalItems).length,4);assert.equal(r.approvalItems.physics_lab,undefined);assert.equal(r.approvalItems.chemistry_lab,undefined);assert.ok(Object.values(r.approvalItems).filter(i=>i.teacherUid).every(i=>i.teacherUid===accounts.teacher2.uid));});
test('wrong teacher cannot approve; rejection notifies only owner and resubmits with reason history',async()=>{const key='subject_'+offers[1].id;assert.equal((await api('subject_faculty',`/api/requests/${requestId}/actions`,{action:'stage1',approvalId:key,decision:'approved'})).status,403);assert.equal((await api('teacher2',`/api/requests/${requestId}/actions`,{action:'stage1',approvalId:key,decision:'rejected',reason:''})).status,400);assert.equal((await api('teacher2',`/api/requests/${requestId}/actions`,{action:'stage1',approvalId:key,decision:'rejected',reason:'Assignment pending'})).status,200);const notice=await database.collection('notifications').findOne({requestId});assert.equal(notice.studentId,students[1].uid);assert.equal(notice.reason,'Assignment pending');assert.equal(await database.collection('notifications').countDocuments({studentId:students[0].uid,requestId}),0);assert.equal((await api('student1',`/api/requests/${requestId}/actions`,{action:'resubmit'})).status,200);});
test('parallel Stage 1 transactions lead to Mentor, HOD, Office and issuance history',async()=>{const r=(await store.doc('noDueRequests/'+requestId).get()).data();const responses=await Promise.all(Object.entries(r.approvalItems).map(([key,item])=>api(item.approverType==='subject_faculty'?'teacher2':key,`/api/requests/${requestId}/actions`,{action:'stage1',approvalId:key,decision:'approved'})));assert.ok(responses.every(r=>r.status===200),JSON.stringify(responses.map(r=>r.body)));assert.equal((await store.doc('noDueRequests/'+requestId).get()).data().status,'pending_mentor');for(const action of ['mentor','hod'])assert.equal((await api(action,`/api/requests/${requestId}/actions`,{action,decision:'approved'})).status,200);assert.equal((await api('office',`/api/requests/${requestId}/actions`,{action:'issue'})).status,200);assert.equal((await store.doc('noDueRequests/'+requestId).get()).data().status,'issued');assert.ok(await database.collection('hallTickets').findOne({_id:requestId}));assert.equal((await api('office',`/api/requests/${requestId}/actions`,{action:'issue'})).status,403);});
test('office name, email, USN, duplicate counts, filters and issuance status',async()=>{for(const term of ['duplicate','DUPLICATE','Mongo Name']){const response=await api('office','/api/office/search',{term});assert.equal(response.status,200,JSON.stringify(response.body));assert.equal(response.body.count,2);}const filtered=await api('office','/api/office/search',{term:'Duplicate',filters:{section:'B',department:'ISE',semester:'5'}});assert.equal(filtered.body.count,1);assert.equal(filtered.body.rows[0].status.hallTicket,'Issued');for(const term of [students[1].row.usn,students[1].row.collegeEmail])assert.equal((await api('office','/api/office/search',{term})).body.count,1);assert.equal((await api('office','/api/office/search',{term:'NoSuchStudent'})).body.count,0);});
test('Office and students cannot edit profiles, enrollments, marks or roles',async()=>{for(const role of ['office','student1'])for(const path of ['users/'+accounts[role].uid,'students/'+students[1].uid,'offerings/'+offers[1].id,'enrollments/fake','marks/fake'])assert.equal((await api(role,'/api/data/write',{operations:[{type:'set',path,data:{role:'admin',scores:{ia1:30}}}]})).status,403);});
async function browserLogin(role){if(!browser)browser=await chromium.launch({headless:true,channel:'chrome'});const context=await browser.newContext();await context.route('**/js/firebase-config.js',async route=>route.fulfill({contentType:'text/javascript',body:(await readFile('../js/firebase-config.js','utf8')).replaceAll('demo-digital-no-due','demo-mongo-audit').replaceAll(':9199',':9298')}));await context.route('**/js/api-config.js',route=>route.fulfill({contentType:'text/javascript',body:"export const API_BASE_URL='http://127.0.0.1:3001';"}));context.on('request',r=>{assert.ok(!/firestore.googleapis.com|127\.0\.0\.1:(8180|5001)/.test(r.url()),'Frontend must not contact Firestore/Functions: '+r.url());});const page=await context.newPage();page.setDefaultTimeout(45000);page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:5050/login.html');await page.locator('#email').fill(accounts[role].email);await page.locator('#password').fill('DemoPassword123!');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.waitForURL(/dashboard/);return {page,context};}
test('real Chrome login, student academics, teacher roster, Office duplicates and mobile layouts',async()=>{const login=browserLogin;
 const student=await login('student1');await student.page.getByRole('heading',{name:'My Subjects & Teachers'}).waitFor();assert.equal(await student.page.locator('.subject-item').count(),2);await student.page.goto('http://127.0.0.1:5050/academic.html');await student.page.getByRole('heading',{name:'Subjects & Marks'}).waitFor();assert.match(await student.page.locator('#content').innerText(),/IA1/);for(const width of [1366,768,390]){await student.page.setViewportSize({width,height:900});assert.equal(await student.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}await student.context.close();
 const teacher=await login('teacher2');await teacher.page.goto('http://127.0.0.1:5050/academic.html');await teacher.page.locator('.class-button').first().click();await teacher.page.locator('.marks-form').first().waitFor();assert.equal(await teacher.page.locator('.marks-form').count(),2);await teacher.context.close();
 const office=await login('office');await office.page.locator('#usnInput').fill('Duplicate');await office.page.locator('#searchBtn').click();await office.page.getByText('2 students found with this name',{exact:true}).waitFor();assert.equal(await office.page.locator('.office-search-student').count(),2);await office.page.setViewportSize({width:390,height:844});assert.equal(await office.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await office.context.close();
});
test('real Chrome imports teacher, offering and student CSV through preview and confirm',async()=>{
 const actor=await browserLogin('admin');async function upload(type,headers,row){await actor.page.goto('http://127.0.0.1:5050/admin-dashboard.html');await actor.page.locator('#importType').selectOption(type);const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';await actor.page.locator('#importFile').setInputFiles({name:'isolated.csv',mimeType:'text/csv',buffer:Buffer.from(headers.join(',')+'\n'+headers.map(k=>quote(row[k])).join(','))});await actor.page.locator('#previewBtn').click();await actor.page.waitForFunction(()=>document.getElementById('importProgress')?.textContent.startsWith('Preview ready'));assert.match(await actor.page.locator('#importPreview').innerText(),/0 error rows/);await actor.page.locator('#acceptWarnings').check();await actor.page.locator('#importBtn').click();await actor.page.waitForFunction(()=>document.getElementById('importProgress')?.textContent.includes('rows completed'));assert.match(await actor.page.locator('#importProgress').innerText(),/0 failed or skipped/);}
 await upload('teachers',['name','collegeEmail','phone','department','employeeId','role'],{name:'CSV UI Teacher',collegeEmail:'mongo-ui-teacher@demo.test',phone:'9000000000',department:'ISE',employeeId:'MONGO-UI',role:'subject_faculty'});
 await upload('offerings',['department','scheme','semester','section','subjectCode','subjectName','teacherEmail','credits','components'],{department:'ISE',scheme:'2022',semester:5,section:'C',subjectCode:'UIT501',subjectName:'Browser CSV course',teacherEmail:'mongo-ui-teacher@demo.test',credits:4,components:JSON.stringify([{id:'ia1',label:'IA1',max:30},{id:'assignment',label:'Assignment',max:10}])});
 const row={name:'CSV UI Student',usn:'1AY99IS199',collegeEmail:'mongo-ui-student@demo.test',phone:'9000000000',department:'ISE',semester:5,section:'C',scheme:'2022',mentorEmail:accounts.mentor.email};await upload('students',['name','usn','collegeEmail','phone','department','semester','section','scheme','mentorEmail'],row);await upload('students',['name','usn','collegeEmail','phone','department','semester','section','scheme','mentorEmail'],row);const profile=await database.collection('students').findOne({usn:row.usn});assert.ok(profile);assert.equal(await database.collection('students').countDocuments({usn:row.usn}),1);assert.equal(await database.collection('enrollments').countDocuments({studentId:profile._id}),2);await actor.context.close();
});
test('real Chrome completes Student → teachers/Library/Accounts → Mentor → HOD → Office',async()=>{
 const actor=await browserLogin('student0');await actor.page.goto('http://127.0.0.1:5050/create-request.html');await actor.page.locator('#confirmCheck').check();await actor.page.locator('#submitBtn').click();await actor.page.waitForURL(/student-dashboard/);const r=await database.collection('noDueRequests').findOne({studentId:students[0].uid}),id=r._id;
 for(const role of ['subject_faculty','library','accounts']){const approval=await browserLogin(role);await approval.page.goto('http://127.0.0.1:5050/approver-dashboard.html#requests');const key=role==='subject_faculty'?'subject_'+offers[0].id:role;const row=approval.page.locator(`[data-path="noDueRequests/${id}/approvals/${key}"]`);await row.waitFor();await row.locator('.approve-btn').click();for(let i=0;i<100;i++){if((await database.collection('noDueRequests').findOne({_id:id})).approvalStates[key]==='approved')break;await new Promise(r=>setTimeout(r,100));}assert.equal((await database.collection('noDueRequests').findOne({_id:id})).approvalStates[key],'approved');await approval.context.close();}
 for(const role of ['mentor','hod']){const approval=await browserLogin(role);await approval.page.goto(`http://127.0.0.1:5050/${role}-dashboard.html#requests`);const row=approval.page.locator(`[data-request-id="${id}"]`);await row.waitFor();await row.locator('.approve-btn').click();for(let i=0;i<100;i++){if((await database.collection('noDueRequests').findOne({_id:id})).status===(role==='mentor'?'pending_hod':'cleared'))break;await new Promise(r=>setTimeout(r,100));}await approval.context.close();}
 const office=await browserLogin('office');await office.page.locator(`[data-request-id="${id}"]`).click();for(let i=0;i<100;i++){if((await database.collection('noDueRequests').findOne({_id:id})).status==='issued')break;await new Promise(r=>setTimeout(r,100));}assert.equal((await database.collection('noDueRequests').findOne({_id:id})).status,'issued');await actor.page.reload();await actor.page.getByText('Hall ticket issued',{exact:false}).first().waitFor();await office.context.close();await actor.context.close();
});
test('MongoDB never stores passwords and rejects Mongo operator injection',async()=>{for(const name of ['users','students','provisioningJobs'])assert.ok(!JSON.stringify(await database.collection(name).find({}).toArray()).includes('DemoPassword123!'));assert.equal((await api('student1','/api/data/query',{path:'students',filters:[['uid','==',{$ne:null}]]})).status,400);});
test('reimport preserves existing marks and explicit resource routes enforce ownership',async()=>{const before=await database.collection('marks').find({}).sort({_id:1}).toArray();await admin({action:'importOffering',row:offers[1].row});await admin({action:'provision',row:students[1].row,requestId:'marks-preserve-repeat'});assert.deepEqual(await database.collection('marks').find({}).sort({_id:1}).toArray(),before);const bearer=await token(accounts.student1.email);assert.equal((await request(app).get('/api/students/'+students[1].uid).set('Authorization','Bearer '+bearer)).status,200);assert.equal((await request(app).get('/api/students/'+students[0].uid).set('Authorization','Bearer '+bearer)).status,403);assert.equal((await request(app).get('/api/hall-tickets').set('Authorization','Bearer '+bearer)).body.rows.length,1);assert.equal((await api('mentor','/api/data/read',{path:'offerings/'+offers[1].id})).status,200);});
test('production provisioning uses activation and never returns or stores a demo password',async()=>{const original=(await store.doc('settings/institution').get()).data(),delivered=[];try{await store.doc('settings/institution').set({allowedDomains:['college.invalid'],departments:['ISE'],sections:['A','B','C']});const service=createProvisioner({db:store,auth,demo:false,sendActivation:async(email,link)=>delivered.push({email,link})}),result=await service.dispatch(accounts.admin.uid,{action:'importTeacher',row:{name:'Activation Audit Teacher',collegeEmail:'activation@college.invalid',phone:'9000000000',department:'ISE',employeeId:'ACTIVATION-AUDIT',role:'subject_faculty'}});assert.equal(result.activation,'sent');assert.equal(result.demoPassword,undefined);assert.equal(delivered.length,1);assert.ok(delivered[0].link.includes('mode=resetPassword'));assert.ok(!JSON.stringify(await database.collection('provisioningJobs').find({}).toArray()).includes('DemoPassword123!'));}finally{await store.doc('settings/institution').set(original);}});
test('Firebase forgot/change password still work independently of MongoDB',async()=>{const email=accounts.student2.email,profile=await database.collection('students').findOne({_id:accounts.student2.uid});async function authRest(action,body){const r=await fetch(`http://127.0.0.1:9298/identitytoolkit.googleapis.com/v1/accounts:${action}?key=fake-api-key`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};}assert.equal((await authRest('sendOobCode',{requestType:'PASSWORD_RESET',email})).status,200);const codes=await(await fetch('http://127.0.0.1:9298/emulator/v1/projects/demo-mongo-audit/oobCodes')).json(),code=codes.oobCodes.filter(c=>c.email===email).at(-1);assert.ok(code);assert.equal((await authRest('resetPassword',{oobCode:code.oobCode,newPassword:'AuditChanged123!'})).status,200);assert.equal((await authRest('signInWithPassword',{email,password:'DemoPassword123!',returnSecureToken:true})).status,400);const login=await authRest('signInWithPassword',{email,password:'AuditChanged123!',returnSecureToken:true});assert.equal(login.status,200);assert.equal((await authRest('update',{idToken:login.data.idToken,password:'DemoPassword123!',returnSecureToken:true})).status,200);assert.ok(await token(email));assert.deepEqual(await database.collection('students').findOne({_id:accounts.student2.uid}),profile);});
test('Chrome student sees updated marks, mentor sees mentee academics and Office sees issuance history',async()=>{
 const score=(await database.collection('marks').findOne({studentId:students[1].uid,offeringId:offers[1].id})).scores.ia1;
 const student=await browserLogin('student1');await student.page.goto('http://127.0.0.1:5050/academic.html');const section=student.page.locator('.academic-subject').filter({hasText:'TEST501'});await section.waitFor();assert.equal(await section.locator('tr').filter({hasText:'IA1'}).locator('td').nth(1).innerText(),String(score));await student.context.close();
 const mentor=await browserLogin('mentor');await mentor.page.goto('http://127.0.0.1:5050/academic.html');await mentor.page.getByRole('heading',{name:'My mentees'}).waitFor();await mentor.page.locator(`a[href="academic.html?student=${students[1].uid}"]`).click();await mentor.page.getByRole('heading',{name:'Subjects & Marks'}).waitFor();assert.match(await mentor.page.locator('#content').innerText(),/TEST501/);await mentor.context.close();
 const history=await request(app).get('/api/hall-tickets').set('Authorization','Bearer '+await token(accounts.office.email));assert.equal(history.status,200);assert.equal(history.body.rows.length,2);
});
