// MongoDB repository exposing the document operations used by the proven domain services.
import {randomUUID} from 'node:crypto';
const mapping={settings:'institutionPolicy'};
export function location(path){const parts=path.split('/');if(parts.length===2)return {collection:mapping[parts[0]]||parts[0],id:parts[1]};if(parts.length===4&&parts[0]==='students'&&parts[2]==='clearance')return {collection:'clearancePlans',id:parts[1],parent:parts[1]};if(parts.length===4&&parts[2]==='approvals')return {collection:'approvals',id:parts[1]+'/'+parts[3],parent:parts[1]};if(parts.length===4&&parts[0]==='users'&&parts[2]==='notifications')return {collection:'notifications',id:parts[1]+'/'+parts[3],parent:parts[1]};throw new Error('Unsupported document path.');}
export function collectionLocation(path){const parts=path.split('/');return parts.length===1?{collection:mapping[path]||path}:location(path+'/placeholder');}
function clean(value){if(!value)return undefined;const {_id,__parent,...data}=value;return data;}
function merge(old,patch){const next={...old};for(const [key,value]of Object.entries(patch)){if(value===undefined)continue;if(value?.__operation==='arrayRemove')next[key]=(next[key]||[]).filter(v=>!value.values.includes(v));else next[key]=value;}return next;}
class Snapshot{constructor(ref,data){this.ref=ref;this.id=ref.id;this.exists=!!data;this.value=clean(data);}data(){return this.value;}}
class Ref{constructor(store,path){this.store=store;this.path=path;this.id=path.split('/').at(-1);this.key=location(path);}collection(name){return new Query(this.store,this.path+'/'+name);}async get(){const d=await this.store.database.collection(this.key.collection).findOne({_id:this.key.id},{session:this.store.session});return new Snapshot(this,d);}async set(data,options={}){return this.store.write(this,'set',data,options);}async update(data){return this.store.write(this,'update',data,{merge:true});}async delete(){return this.store.write(this,'delete');}}
class Query{constructor(store,path,filters=[],orders=[],maximum=null,cursor=null){Object.assign(this,{store,path,filters,orders,maximum,cursor});}clone(patch){return Object.assign(new Query(this.store,this.path,this.filters,this.orders,this.maximum,this.cursor),patch);}doc(id=randomUUID()){return new Ref(this.store,this.path+'/'+id);}where(field,op,value){return this.clone({filters:[...this.filters,[field,op,value]]});}orderBy(field,direction='asc'){return this.clone({orders:[...this.orders,[field,direction]]});}limit(maximum){return this.clone({maximum});}startAfter(cursor){return this.clone({cursor});}async get(){const loc=collectionLocation(this.path),criteria=[];if(loc.parent)criteria.push({__parent:loc.parent});for(const [field,op,value]of this.filters){const f=field==='__name__'?'_id':field;criteria.push(op==='=='?{[f]:value}:op==='in'?{[f]:{$in:value}}:op==='array-contains'?{[f]:value}:op==='>='?{[f]:{$gte:value}}:op==='<='?{[f]:{$lte:value}}:(()=>{throw new Error('Unsupported query operator');})());}const sort=Object.fromEntries((this.orders.length?this.orders:[['__name__','asc']]).map(([f,d])=>[f==='__name__'?'_id':f,d==='desc'?-1:1]));if(this.cursor){const id=this.cursor.key?.id||this.cursor.ref?.key?.id||this.cursor.id||this.cursor;criteria.push({_id:{$gt:loc.parent?loc.parent+'/'+String(id).split('/').at(-1):id}});}let query=this.store.database.collection(loc.collection).find(criteria.length?{$and:criteria}:{},{session:this.store.session}).sort(sort);if(this.maximum)query=query.limit(this.maximum);const rows=await query.toArray(),docs=rows.map(row=>new Snapshot(new Ref(this.store,this.path+'/'+String(row._id).split('/').at(-1)),row));return {docs,size:docs.length,empty:!docs.length};}}
export class DocumentStore{constructor(database,client,session=null){Object.assign(this,{database,client,session});}doc(path){return new Ref(this,path);}collection(path){return new Query(this,path);}async write(ref,operation,data={},options={}){const {collection,id,parent}=ref.key,table=this.database.collection(collection),session=this.session;if(operation==='delete')return table.deleteOne({_id:id},{session});const old=options.merge?(await table.findOne({_id:id},{session})):null;if(operation==='update'&&!old)throw new Error('Record does not exist.');const next=options.merge?merge(clean(old)||{},data):merge({},data);if(collection==='users')next.firebaseUid=id;await table.replaceOne({_id:id},{...next,_id:id,...(parent?{__parent:parent}:{})},{upsert:true,session});}
  batch(){const operations=[];const batch={set:(ref,data,options)=>operations.push([ref,'set',data,options]),update:(ref,data)=>operations.push([ref,'update',data,{merge:true}]),delete:ref=>operations.push([ref,'delete']),commit:()=>this.runTransaction(async tx=>{for(const [ref,op,data,opts]of operations)await tx.store.write(tx.store.doc(ref.path),op,data,opts);})};return batch;}
  async runTransaction(callback){const execute=async store=>{const tx=store.transaction(),result=await callback(tx);await tx.flush();return result;};if(this.session)return execute(this);const session=this.client.startSession();try{let result;await session.withTransaction(async()=>{result=await execute(new DocumentStore(this.database,this.client,session));});return result;}finally{await session.endSession();}}
  transaction(){const writes=[];let reads=Promise.resolve();return {store:this,get:ref=>{const read=reads.then(()=>ref instanceof Query?ref.clone({store:this}).get():this.doc(ref.path).get());reads=read.catch(()=>{});return read;},set:(ref,data,options)=>writes.push(()=>this.write(this.doc(ref.path),'set',data,options)),create:(ref,data)=>writes.push(()=>this.database.collection(ref.key.collection).insertOne({...merge({},data),_id:ref.key.id,...(ref.key.parent?{__parent:ref.key.parent}:{})},{session:this.session})),update:(ref,data)=>writes.push(()=>this.write(this.doc(ref.path),'update',data,{merge:true})),delete:ref=>writes.push(()=>this.write(this.doc(ref.path),'delete')),flush:async()=>{await reads;for(const write of writes)await write();}};}
}
