import {randomUUID} from 'node:crypto';
import {enrollmentPlan,syncStudentWorkflow} from './clearance.js';
import {stage1Change,resumeChange,STATUS} from './workflow-model.js';
const fail=message=>{throw Object.assign(new Error(message),{code:'permission-denied'});};
export async function submitRequest(store,actor){if(actor.role!=='student')fail('Only students submit requests.');await syncStudentWorkflow(store,actor.uid);const plan=await enrollmentPlan(store,actor.uid),student=(await store.doc(`students/${actor.uid}`).get()).data(),id=randomUUID();await store.runTransaction(async tx=>{const request={schemaVersion:2,workflowVersion:3,studentId:actor.uid,studentName:student.name,usn:student.usn,semester:student.semester,section:student.section,mentorId:plan.mentorId,hodId:plan.hodId,officeId:plan.officeId,approverIds:plan.approverIds,approvalItems:plan.items,approvalStates:plan.initialStates,resubmissionStates:plan.initialStates,remaining:Object.keys(plan.items).length,status:STATUS.PENDING_STAGE1,mentorApproval:{status:'pending',remarks:''},hodApproval:{status:'pending',remarks:''},version:0,lastApprovalId:'',lastEvent:null,createdAt:new Date()};tx.create(store.doc(`noDueRequests/${id}`),request);for(const [key,item]of Object.entries(plan.items))tx.set(store.doc(`noDueRequests/${id}/approvals/${key}`),{...item,status:'pending',remarks:'',actedBy:null,actedAt:null,studentId:actor.uid,studentName:student.name,usn:student.usn,section:student.section,requestId:id});});return {id};}
export async function requestAction(store,actor,id,input){
  if(!/^[A-Za-z0-9_-]{1,128}$/.test(id))fail('Invalid request.');const action=input.action,decision=input.decision,reason=String(input.reason||'').trim();if(reason.length>2000||['stage1','mentor','hod'].includes(action)&&(!['approved','rejected'].includes(decision)||decision==='rejected'&&!reason))throw Object.assign(new Error('A valid decision and rejection reason are required.'),{code:'invalid-argument'});
  await store.runTransaction(async tx=>{const ref=store.doc(`noDueRequests/${id}`),r=(await tx.get(ref)).data();if(!r)fail('Request not found.');let patch,key,keys=[],approvalDecision=decision;
    if(action==='stage1'){key=input.approvalId;const item=r.approvalItems?.[key];if(!item||item.approverId!==actor.uid||!['subject_faculty','mentor','library','accounts'].includes(actor.role)||!['subject_faculty','library','accounts'].includes(item.approverType))fail('This item is not assigned to you.');if(item.approverType==='subject_faculty'){const plan=await enrollmentPlan(tx.store,r.studentId);if(plan.items[key]?.approverId!==actor.uid||plan.items[key]?.offeringId!==item.offeringId)fail('Teacher offering changed. Refresh the mapping.');}patch=stage1Change(r,key,decision);keys=[key];}
    else if(action==='mentor'||action==='hod'){const mentor=action==='mentor',owner=mentor?'mentorId':'hodId',field=mentor?'mentorApproval':'hodApproval',stage=mentor?'pending_mentor':'pending_hod';if(actor.role!==action||r[owner]!==actor.uid||r.status!==stage)fail('This request is not at your assigned stage.');patch={[field]:{status:decision,remarks:reason,actorId:actor.uid,actedAt:new Date()},status:decision==='rejected'?'rejected':mentor?'pending_hod':'cleared'};}
    else if(action==='issue'){if(actor.role!=='office'||r.officeId!==actor.uid||r.status!=='cleared')fail('Only assigned Office can issue a cleared request.');patch={status:'issued',issuedBy:actor.name,issuedById:actor.uid,issuedAt:new Date()};tx.create(store.doc(`hallTickets/${id}`),{requestId:id,studentId:r.studentId,usn:r.usn,issuedById:actor.uid,issuedAt:patch.issuedAt});}
    else if(action==='resubmit'){if(actor.role!=='student'||r.studentId!==actor.uid)fail('This request does not belong to you.');patch=resumeChange(r);keys=patch.approvalStates?Object.keys(r.approvalStates).filter(k=>r.approvalStates[k]==='rejected'):[];approvalDecision='pending';}
    else fail('Unknown request action.');
    const version=(r.version||0)+1,event={requestId:id,studentId:r.studentId,actorId:actor.uid,actorName:actor.name||'',actorType:actor.role,subjectCode:key?r.approvalItems[key].subjectCode||null:null,reason,status:patch.status,version,createdAt:new Date()};tx.update(ref,{...patch,version,lastEvent:event,updatedAt:new Date()});tx.set(store.doc(`users/${r.studentId}/notifications/${id}_${version}`),event);for(const k of keys)tx.set(store.doc(`noDueRequests/${id}/approvals/${k}`),{...r.approvalItems[k],studentId:r.studentId,studentName:r.studentName,usn:r.usn,section:r.section,requestId:id,status:approvalDecision,remarks:reason,actedBy:actor.name||'',actorId:actor.uid,actedAt:new Date()},{merge:true});
  });return {saved:true};
}
