// Read-only browser acceptance against the migrated local demo. Never clicks mutations.
import assert from 'node:assert/strict';
import {MongoClient} from 'mongodb';
import {chromium} from 'playwright';
import {writeFile} from 'node:fs/promises';
const client=new MongoClient('mongodb://127.0.0.1:27017/digital_no_due_dev?replicaSet=rs0');await client.connect();const db=client.db(),report={students:[],teachers:[],errors:[]};let browser;
const protectedCollections=['marks','enrollments','noDueRequests','approvals','notifications','hallTickets'];
async function snapshot(){return Object.fromEntries(await Promise.all(protectedCollections.map(async name=>[name,await db.collection(name).find({}).sort({_id:1}).toArray()])));}
async function login(email){const context=await browser.newContext(),page=await context.newPage();page.setDefaultTimeout(45000);context.on('request',r=>assert.ok(!/firestore.googleapis.com|127\.0\.0\.1:(8180|5001)/.test(r.url()),r.url()));page.on('pageerror',e=>report.errors.push(e.message));await page.goto('http://127.0.0.1:5050/login.html');await page.locator('#email').fill(email);await page.locator('#password').fill('DemoPassword123!');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.waitForURL(/dashboard/);return {context,page};}
try{const before=await snapshot();browser=await chromium.launch({headless:true,channel:'chrome'});
 for(const usn of ['1AY24IS156','1AY24IS157','1AY24IS158']){const s=await db.collection('students').findOne({usn});assert.ok(s,usn);const actor=await login(s.email);await actor.page.getByRole('heading',{name:'My Subjects & Teachers'}).waitFor();const expected=await db.collection('enrollments').countDocuments({studentId:s._id,active:true});assert.equal(await actor.page.locator('.subject-item').count(),expected,usn);await actor.page.goto('http://127.0.0.1:5050/academic.html');await actor.page.getByRole('heading',{name:'Subjects & Marks'}).waitFor();assert.match(await actor.page.locator('#content').innerText(),/BCS/);report.students.push({usn,section:s.section,subjects:expected});await actor.context.close();}
 for(const email of ['aarav.mehta@demo.test','nida.farooq@demo.test','rohit.kulkarni@demo.test','sana.mir@demo.test','vivek.reddy@demo.test']){const teacher=await db.collection('users').findOne({email});assert.ok(teacher);const actor=await login(email);await actor.page.goto('http://127.0.0.1:5050/academic.html');const offerings=await db.collection('offerings').find({teacherId:teacher._id,active:true}).toArray();await actor.page.locator('.class-button').first().waitFor();const rosters=[];for(let i=0;i<offerings.length;i++){const button=actor.page.locator('.class-button').nth(i);await button.click();await actor.page.locator('.marks-form').first().waitFor();const current=await button.getAttribute('data-id'),o=offerings.find(o=>o._id===current);assert.ok(o);const expected=Math.min(30,await db.collection('enrollments').countDocuments({offeringId:o._id,teacherId:teacher._id,active:true}));const shown=await actor.page.locator('.marks-form').count();assert.equal(shown,expected,o._id);for(const form of await actor.page.locator('.marks-form').all())assert.ok((await form.innerText()).includes('Section '+o.section));rosters.push({offeringId:o._id,section:o.section,students:shown});assert.ok(shown>1,'Roster must contain more than a temporary test student');}report.teachers.push({email,rosters});await actor.context.close();}
 assert.deepEqual(await snapshot(),before,'Protected migrated records changed during read-only acceptance');assert.deepEqual(report.errors,[]);report.protectedDataUnchanged=true;report.passed=true;console.log(JSON.stringify(report,null,2));
}finally{await writeFile(new URL('../test/current-browser-results.json',import.meta.url),JSON.stringify(report,null,2));await browser?.close();await client.close();}

